### ISSUE TITLE
达到限制阈值后, 只有提醒, 不能停止充电

### ISSUE THREAD

**Issue by CangWeiohh** [lich4/AlDente#10]
iPhone 12
iOS 15.4
巨魔 + Dopamine越狱

达到限制阈值后, 只有提醒, 不能停止充电, 还是继续增长, 电流也没有变化

**Comment by lich4** [comment]
手头没有11以上的型号，暂时无法帮你解决

**Comment by CangWeiohh** [comment]
> 手头没有11以上的型号，暂时无法帮你解决

好吧

**Comment by lich4** [comment]
最近有13型号的反馈可以用，你看看是否与更新频率设置有关，决定灵敏度的

**Comment by lich4** [comment]
1. 按文档给出方式确定手机电池是否支持
2. 安装v1.3及以上版本，避免受系统优化电池干扰
