### ISSUE TITLE
手动充电的那个按钮反应非常迟钝

### ISSUE THREAD

**Issue by lxr760** [lich4/AlDente#11]
比如我是设置20%充电，80%停止充电

电量是30%的时候我想充电，这时候去点app里那个充电按钮，点击或者滑动都会没有反应，要不停的去点，然后突然就可以了

**Comment by lich4** [comment]
重复https://github.com/lich4/AlDente/issues/8#issuecomment-1930063797

**Comment by lxr760** [comment]
> 重复[#8 (comment)](https://github.com/lich4/AlDente/issues/8#issuecomment-1930063797)

我是ios15.5  也有这个问题

**Comment by lich4** [comment]
贴出你的型号系统版本等基础信息。我要综合判断到底与型号有关还是跟16系统有关

**Comment by lxr760** [comment]
> 贴出你的型号系统版本等基础信息。我要综合判断到底与型号有关还是跟16系统有关。现在手头型号有限，需要更多数据

iPhone 13 Pro Max iOS 15.5

AlDente 1.0.1

**Comment by lich4** [comment]
经过分析内核源码，发现与系统无关，与型号有关，实测11型号存在延迟120秒更新，7型号没有。具体从哪个型号开始的还不确定，可能是X或11

**Comment by lxr760** [comment]
> 经过分析内核源码，发现与系统无关，与型号有关，实测11型号存在延迟120秒更新，7型号没有。具体从哪个型号开始的还不确定，可能是X或11，不过这非软件本身bug，我也不确定是否能“修复”，持续关注本项目吧

这个延迟是不是也会导致app显示的数据也不会自动刷新，比如电流那项，非得后台删掉再进去数值才变化

**Comment by lich4** [comment]
1.1版修复

**Comment by lich4** [comment]
iPhone8及以上型号存在最大120秒刷新周期，所以不能立刻刷新状态
