### ISSUE TITLE
Build error: 'IORegistryEntrySetCFProperties' has been explicitly marked unavailable here

### ISSUE THREAD

**Issue by tageniu** [lich4/AlDente#16]
I tried to build the app but got error inside `setChargeStatus` function "'`IORegistryEntrySetCFProperties`' has been explicitly marked unavailable here". I also tried `IOConnectSetCFProperties` but not work either. Is seems the functions are marked `__UNAVAILABLE_PUBLIC_IOS` in IOKitLib.h, so how can I build the app?

**Comment by lich4** [comment]
It's a private api. You need Theos development environment
