### ISSUE TITLE
deb安装，简体中文设置不能保存

### ISSUE THREAD

**Issue by ljwbh** [lich4/AlDente#18]
非常感谢，该软件越来越人性化，只是提个小小BUG，若用deb安装后，功能没问题，只是设置简体中文，然后退出重进，又回到了ZH;Trollstore安装，没有此问题。

**Comment by lich4** [comment]
下一版修复。具体现象再描述清楚一些，是关闭服务触发，还是关闭app就触发？

**Comment by ljwbh** [comment]
没有关闭服务，运行后，只是把语言设为简体中文，无论那个模式，把程序从后台退出，然后再进，语言又变成默认ZH
