### ISSUE TITLE
1.2版本看上去很完善很好用了，点赞👍！对于一直插电的场景，能否改供电为电源而不是电池呢？

### ISSUE THREAD

**Issue by boli2017** [lich4/AlDente#19]
这样有两个好处，一是一直插电使用不会消耗电池健康和增加循环次数，二是老设备可以无顾虑作为车机carplay

**Comment by lich4** [comment]
iOS上没有Mac上的接口，因此应用态无法实现

**Comment by lich4** [comment]
iOS上并没有提供复杂的电源管理接口，因此无法实现Mac上完全相同的效果，这点和Mac是不同的，iOS上此方案不可行。如果有的话，这类工具也早就存在了，接口相同的情况下，从Mac上迁移到iOS并不是非常复杂。正因为iOS系统的封闭性，因此是需要通过逆向去研究的，这正是本人所擅长的。
       其次本工具主要功能是防止过充而非其他，本人比较忙，对于公益项目不可能投入太多时间，原计划就是一个一天的项目，这几天是假期所以又花了几天时间做完善。
       另外你如果真喜欢此项目，可以动动小手为本项目点个star。
