### ISSUE TITLE
Ideas for the next update 

### ISSUE THREAD

**Issue by hezz79** [lich4/AlDente#21]
If possible, add dark mode support and let us be able to set % to any value instead of being locked to only 5% increments in the next update. Thanks.

**Comment by lich4** [comment]
Why 1% is meaning so much? I thought 5% is enough.

**Comment by hezz79** [comment]
It’s okay, I understand. I’ve seen your other reply on the matter. Nice project you have here. 👏🏽👏🏽

**Comment by lich4** [comment]
Thanks
