### ISSUE TITLE
使用smart battery case为iPhone充电软件显示问题？

### ISSUE THREAD

**Issue by BugGust** [lich4/AlDente#22]
设备：iPhone13 mini
系统：iOS16.6.1
软件版本：1.2
使用smart battery case为iPhone充电的话正在充电开关无法正常使用(提示需要连接电源）但边缘触发和插电充电限制依旧正常生效，下图是使用smart battery case充电是软件显示的信息，和普通充电宝的区别就是正在充电和电源信息的电源已连接一直为关闭(即使已经接入电源)，希望作者有空修复下🙏
![IMG_1974](https://github.com/lich4/AlDente/assets/155085748/0fec13e0-e2b7-4905-a4d5-0390f84228db)
![IMG_1975](https://github.com/lich4/AlDente/assets/155085748/295d3965-1deb-434a-9082-dcb7d6d675a6)

**Comment by lich4** [comment]
这不属于显示问题，app中显示的数据都是内核中的数据。
由于我手上没有这种设备，不太好修复啊

**Comment by BugGust** [comment]
> 这不属于显示问题，app中显示的数据都是内核中的数据。
> 由于我手上没有这种设备，不太好修复啊

或许是iOS给smart battery case单独设置了一套逻辑吧，那两个模式还是可以正常限制充电的，影响不大

**Comment by lich4** [comment]
1.4.1已修复

**Comment by BugGust** [comment]
> 1.4.1已修复
设备：iPhone13 mini
系统：iOS16.6.1
软件版本：1.4.1
经个人测试问题并没有解决，我尝试过卸载软件-重启手机-重新安装软件，可是戴上smart battery case充电不会停止，手动切换正在充电按钮，倒数完毕后按钮仍一直处于关闭状态，但还是有电流通，如图。
![IMG_2378](https://github.com/lich4/ChargeLimiter/assets/155085748/331b9c5c-1027-4b0e-b544-3073e936ed7c)
![IMG_2379](https://github.com/lich4/ChargeLimiter/assets/155085748/595774c8-4cf7-4c59-bf03-94c9846c4adf)

**Comment by BugGust** [comment]
> 1.4.1已修复

设备：iPhone13 mini
系统：iOS16.6.1
软件版本：1.4.1
经个人测试问题并没有解决，我尝试过卸载软件-重启手机-重新安装软件，可是戴上smart battery case充电不会停止，手动切换正在充电按钮，倒数完毕后按钮仍一直处于关闭状态，观察电池状态有电流通，如图。
![IMG_2378](https://github.com/lich4/ChargeLimiter/assets/155085748/9461f842-1c14-4ff2-b31d-823072252b2b)
![IMG_2379](https://github.com/lich4/ChargeLimiter/assets/155085748/ef6e69d8-1c49-4e29-9c37-b8b5b53df3f8)

**Comment by lich4** [comment]
手动切换按钮都不生效，说明电池不支持啊。
多问一句，如果不用smart battery case而直接用电源充电，手动按钮生效不？

**Comment by BugGust** [comment]
> 手动切换按钮都不生效，说明电池不支持啊。因为你上次提交的问题是不支持你这种电源，现在是识别这种电源的。但你手动按钮不生效就不是软件问题了。
> 多问一句，如果不用smart battery case而直接用电源充电，手动按钮生效不？
> 你之前不是2个模式都生效的吗？如果模式生效的话手动切换肯定也是生效的。怎么新版手动切换不行了呢

很抱歉这么晚才回复，

> 如果不戴smart battery case直接接入充电线的话，切换正在充电按钮是正常生效的。

>  容我纠正一下之前两个模式都生效的说法，所以我花时间做了点测试来说明：

首先，戴上smart battery case，再将充电线接入smart battery case的话，正在充电按钮就生效了，此时将正在充电设置为停止，再拔掉充电线的话，smart battery case对iPhone的充电就停止了，软件显示如图
![IMG_2394](https://github.com/lich4/ChargeLimiter/assets/155085748/b0b3a562-d3b5-46fe-be9e-21b2fdcfb705)

另外，我发现如果在使用边缘模式的时候戴上smart battery case后再切换回插电即冲模式，smart battery case对iPhone的充电也会停止，软件显示如图
![IMG_2395](https://github.com/lich4/ChargeLimiter/assets/155085748/825ec37b-e3cf-41b2-bd42-ea1b20ee0046)

而正好我两个模式都有用，之前测试充电暂停或许是这个问题导致的，导致我误解以为模式的暂停充电是生效的，实际如果不切换模式，smart battery case会一直为iPhone冲到满电，并不受软件影响。

**Comment by BugGust** [comment]
> 手动切换按钮都不生效，说明电池不支持啊。因为你上次提交的问题是不支持你这种电源，现在是识别这种电源的。但你手动按钮不生效就不是软件问题了。
> 多问一句，如果不用smart battery case而直接用电源充电，手动按钮生效不？
> 你之前不是2个模式都生效的吗？如果模式生效的话手动切换肯定也是生效的。怎么新版手动切换不行了呢

很抱歉这么晚才回复，

＞ 如果不戴smart battery case直接接入充电线的话，切换正在充电按钮是正常生效的。

＞ 容我纠正一下之前两个模式都生效的说法，所以我花时间做了点测试来说明
首先，戴上smart battery case，再将充电线接入smart battery case的话，正在充电按钮就生效了，此时将正在充电设置为停止，再拔掉充电线的话，smart battery case对iPhone的充电就停止了，软件显示如图
![IMG_2394](https://github.com/lich4/ChargeLimiter/assets/155085748/0e59f6d0-1ae8-4855-9765-8035484d2c88)

另外，我发现如果在使用边缘模式的时候戴上smart battery case后再切换回插电即冲模式，smart battery case对iPhone的充电也会停止，软件显示如图
![IMG_2395](https://github.com/lich4/ChargeLimiter/assets/155085748/e4f56f40-94af-4e6b-9582-e48d04ac830b)

而正好我两个模式都有用，之前测试充电暂停或许是这个问题导致的，导致我误解以为模式的暂停充电是生效的，实际如果不切换模式，smart battery case会一直为iPhone冲到满电，并不受软件影响。
