### ISSUE TITLE
电量低于（%）开始充电

### ISSUE THREAD

**Issue by Allen1iu99** [lich4/AlDente#4]
这个按照字面意思是电量低于X%才开始充电，实际上设置20%，但是实际80%电量也能冲进电。
<img width="432" alt="iShot_2024-02-04_16 33 22" src="https://github.com/lich4/AlDente/assets/89820291/e90728dd-5555-43d8-8079-15e6a2d0bec1">
<img width="402" alt="iShot_2024-02-04_16 35 14" src="https://github.com/lich4/AlDente/assets/89820291/e4f901e5-9ccb-44af-a6bb-8b7f5447a0b1">

我猜测您想实现的应该是续航模式吧，换个描述会不会更容易懂一点，个人建议

**Comment by lich4** [comment]
AlDente我是前天才开始用，没有太搞明白续航模式。我采用了最简单的构想，模拟真实设备没电了就去充的这种状态，即低于某个阈值开始充电，高于某个阈值停止。AlDente是实现了防抖动，防止电量突然掉下去导致反复充电。我是看了几个文章说电量保持在20-80之间最好，所以就这么设置的，这个可以自己调整的

**Comment by mraxu** [comment]
确实也遇见了这个描述问题，如果我设置了20%充电（下限），然后我设置了70%（上限）
如果我的手机突然想从70%充电冲到80%，但是没有掉电到20%的下限的话，只能调高下限到70%以上才能充电
不过这个软件毕竟目前比较小众，持续关注大佬的描述改善

**Comment by lich4** [comment]
大概知道你说的啥意思了，目前我这个逻辑是“边缘触发”，即低于20%且发现没充电才开始充电，高于80%发现还在充电就停止充电。如果处于20-80之间则保持原始状态的充电或者不充电，因为我想模拟在手机户外的情况，尽可能让其减少充电次数。当然我也不知道让电量掉到20然后充到80好，还是在20-80之间也要补充到80，我觉得还是范围大点好一些，不过如果有证据表明范围越小越好，比如60-80之间冲放电最好，请告知我。
