### ISSUE TITLE
我有一些疑问希望能得到回复

### ISSUE THREAD

**Issue by InnovatorPrime** [lich4/AlDente#5]
据我了解

AlDente mac版是通过一个后台常驻进程，不断循环检测当前电量，如果电量高于用户设定值，则向 SMC 中 CH0B 这个 key 里写入 `01` 以停止充电，反之则写入 `00` 使电池开始充电。

ios版是否也遵守上述规则？所以目前AlDente ios版也是必须要保持在后台运行吗？

有考虑过使用 bclm 是往 SMC 里 CHWA 这个 key 里写入数值（ 80 or 100 ），直接设定充电上限，从而 bclm 不需要常驻后台不断检测电量。这种逻辑吗？

谢谢！

**Comment by lich4** [comment]
AlDente源码我也大概看过，不过iOS端的我是逆向powerd系统进程得到的，iOS里的方法显然更简单，所以我也没测试AlDente那套底层接口。毕竟iOS是闭源的，是否底层都需要越狱或者巨魔来获取更高权限

**Comment by lich4** [comment]
经测试iOS不存在AppleSMC服务因此Mac上的方案不可行，谢谢关注
