### ISSUE TITLE
IOS版本BUG反馈

### ISSUE THREAD

**Issue by lxr760** [lich4/AlDente#6]
1、软件界面上有个检测时间，可以选1s 10s 1min 10min，但是如果把app后台划掉，再进入还是默认的1min，比如我设置成10s，后台退出的话并不会生效

2、充电的电量会比设置的阈值多1%。比如我设置高于60%停止充电，实际冲到61%才停。设置75%停止，实际76%才停。请问这是否是bug或者app设计即这样，那能否把设置的档位分的更细，1%为一个精度。这样我需要80%的电量，设置里填79%

**Comment by lich4** [comment]
这是我随手开发的工具，功能上差不多即可，不求精确
1. 更新时间并未持久化，这个参数只做显示用，不像上下限那么重要，因此没做持久化
2. 这个与轮训时间有关，每次轮询才会改变充电状态，因此如果检测间隔设置为1分或10分，则期间内如果电池增加了2%，这个就无法控制为只增加1%而不是2%。可以通过减少检测间隔达到更精确的值，个人以为去纠结1%-2%没什么意义，我还有更重要的项目要做。如果你确实有精确到1%的实际需求，请根据源码自行开发定制版。

**Comment by lxr760** [comment]
> 这是我花了1天时间随手开发的工具，功能上差不多即可，不求精确
> 
> 1. 更新时间并未持久化，生命周期和后台进程一致。划掉App未保存确实有点问题我再看看。
> 2. 这个与轮训时间有关，每次轮询才会改变充电状态，因此如果检测间隔设置为1分或10分，则期间内如果电池增加了2%，这个就无法控制为只增加1%而不是2%。可以通过减少检测间隔达到更精确的值，不过太低了应该也会耗点电，个人以为去纠结1%-2%没什么意义，我比较忙，还有更重要的项目要做。如果你确实有精确到1%的实际需求，请根据源码自行开发定制版。

那我设置成60%，实际电量冲到61%，其实是软件的feature而不是bug，可以这样理解？

**Comment by lich4** [comment]
对，不是bug。说明充电速度快于检测周期

**Comment by boli2017** [comment]
很强，这都能被重写！
但是这个和mac上的一个原理吗，假设设置到80，mac看上去是会在80停止充电，而不是80->81,82再从81,82->80，这种其实也会增加电池的循环次数。

**Comment by lich4** [comment]
不是同一个原理，我看过但没参考Mac AlDente的代码，Mac AlDente更底层一些，而我用的是powerd系统进程的接口，他那套更底层接口是否能使用我并没做测试

**Comment by boli2017** [comment]
> 不是同一个原理，我看过但没参考Mac AlDente的代码，Mac AlDente更底层一些，而我用的是powerd系统进程的接口，他那套更底层接口是否能使用我并没做测试

mac版AlDente看上去是充电达到设置阈值之后，是直接控制电源给mac供电而不是电池供电，这种方式就可以减少电池循环了。

**Comment by lich4** [comment]
> mac版AlDente看上去是充电达到设置阈值之后，是直接控制电源给mac供电而不是电池供电，这种方式就可以减少电池循环了。

我开发这个工具的思路，是尽量模拟手机在户外充放电的场景(苹果官方是基于这个场景进行电池优化的)，所以拉大高低2个阈值就能减少充电次数，至于控电方式是从电源还是电池个人觉得可能没那么重要吧，因为咋整都是要充电的

**Comment by smallysin** [comment]
12mini，ios16.3.1，用巨魔安装以后，充电限制无效，实际电量超过阈值以后还是会继续充满

**Comment by lich4** [comment]
> 12mini，ios16.3.1，用巨魔安装以后，充电限制无效，实际电量超过阈值以后还是会继续充满

前台进程不能杀掉，杀掉就不生效了，不过后面会尝试改进

**Comment by smallysin** [comment]
> > 12mini，ios16.3.1，用巨魔安装以后，充电限制无效，实际电量超过阈值以后还是会继续充满
> 
> 前台进程不能滑掉，杀掉就不生效了，不过后面会尝试改进

不对，我的情况是开着软件也无效，没有刻意删后台

**Comment by lich4** [comment]
> 不对，我的情况是开着软件也无效，没有刻意删后台

这个就不好说了，我手头最高只有11型号，没法帮你测。不过高系统的电池管理应该改善好多了

**Comment by hicasper** [comment]
> 好，我有空再研究研究，最近俩月比较忙，有重要的项目要开发。这个项目其实我就是临时玩一下，花了一天开发的，原本没有计划在这上面花更多时间

后台如果长期留存进程的话，对内存和CPU资源消耗会很大吗

**Comment by lich4** [comment]
> 后台如果长期留存进程的话，对内存和CPU资源消耗会很大吗
 那倒不会，后台进程多了去了，咱这个没啥功能占不了很多资源

**Comment by lich4** [comment]
1.1版本修复一些bug

**Comment by lich4** [comment]
> > mac版AlDente看上去是充电达到设置阈值之后，是直接控制电源给mac供电而不是电池供电，这种方式就可以减少电池循环了。
经测试iOS不存在AppleSMC服务因此Mac上的方案不可行，谢谢关注
