### ISSUE TITLE
设置电量达到%停止充电不是即实生效的吗？

### ISSUE THREAD

**Issue by BugGust** [lich4/AlDente#8]
设备：iPhone 13 mini
系统：iOS 16.6.1
在第一次设置达到80%电量停止充电后正常生效，但后续如果调整设置还是会卡在80%电量（即使应用界面ui滑条为100%）我尝试过划掉应用重新打开、重新拔插充电头也一样，如果想要调整生效需要手动到巨魔商店注销才行。

**Comment by lich4** [comment]
软件目前模式是“边缘触发”。如果设置的边界是20-80的话，低于20才会开始充电，高于80才会停止充电，20-80之间是保持原状态的。因此如果修改到20-90的话，因为80处已经停止充电了，所以会保持停止充电直到降到20。 如果想恢复充电，只需切换“正在充电”右侧开关即可，15及以下系统立即更新状态，16系统需要十几秒(系统决定的)。

**Comment by BugGust** [comment]
> 软件目前模式是“边缘触发”。如果设置的边界是20-80的话，低于20才会开始充电，高于80才会停止充电，20-80之间是保持原状态的。因此如果修改到20-90的话，因为80处已经停止充电了，所以会保持停止充电直到降到20。 如果想恢复充电，只需切换“正在充电”右侧开关即可，15及以下系统立即更新状态，16系统需要十几秒(系统决定的)。

谢谢大佬解答，不过这样的模式也有个问题，例如我的使用场景是大部份时间都会携带smart battery case(它会一直充满iPhone以保证后续供电由背甲电池提供）用这个软件可以保证只充到80%并使用背甲电池供电，但有些时候我想让手机充满后单独使用的话问题来了，此时如果我在软件里调整为100%断开的话再充电是不会充电的，因为之前80%的时候软件停止充电了，必须手动切换正在充电开关(这里我想吐槽一下开关，由于我是iOS16它点击一下是不会立马显示切换的，必须等待一会，我也不知道它有没有切换成功就下意识点了好多下，点多了开了又会关掉就很难受😂）非常麻烦，请问能在每次轮询或者重新充电时检测一下设置来做到修改实时生效吗？

**Comment by lich4** [comment]
从目前测试结果看16系统内核电源数据就是20秒才更新，因此重新获取还是旧的，不是应用层能控制的。
如果找到可以强制内核更新数据的我再在此处更新结果(不一定有)

**Comment by lich4** [comment]
经过分析内核源码，发现与系统无关，与型号有关，实测11型号存在延迟120秒更新，7型号没有。具体从哪个型号开始的还不确定，可能是X或11

**Comment by lich4** [comment]
iPhone8及以上型号存在最大120秒刷新周期，所以不能立刻刷新状态
