### ISSUE TITLE
使用场景分析

### ISSUE THREAD

**Issue by Colawater** [lich4/AlDente#9]
普通人使用场景：充电器随充随断，电量充电至 80% 停止。
作者使用场景：充电器一直通电，电量保持在 20% 至 80% 区间，模拟电池正常充放电过程。

其实可以给 下限 做个开关，让 下限 与 上限 脱离关联，这样就可以满足双方使用场景。

谢谢开发！

**Comment by lich4** [comment]
这点下一版本修复

**Comment by lich4** [comment]
1.1版本已修复
